baseURL = "/"
themesDir = "themes"
theme = "hugo-serif-theme"
languageCode = "en-us"
title = "ProDigit"

[module]
[module.hugoVersion]
extended = true
min = "0.55.0"

[params]
# In most cases you will only want to set the google_analytics_id OR the google_tag_manager_id. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
google_analytics_id = ""
google_tag_manager_id = ""
favicon = "favicon-32x32.png"

[params.homepage]
show_contact_box = true      # show / hide the contaxt box on the homepage
show_services_button = false # show / hide the "view all services" button

[params.logo]
mobile = "images/logo/logo-mobile.png"
mobile_height = "36px"
desktop = "images/logo/logo.png"
desktop_height = "36px"
alt = "Serif - A Hugo Business Theme"

[params.fonts]
# sets the google font link in layouts/partials/google-fonts.html
google_fonts = 'https://fonts.googleapis.com/css2?family=Fira+Sans:wght@600&family=Source+Sans+Pro:wght@400;700&display=swap'
heading = "Fira Sans"
base = "Montserrat"

[params.colors]
primary = "#8b2c6e"
black = "#2f2f41"
white = "#ffffff"
white_offset = "#f6f7ff"
grey = "#5C5A5A"

[params.seo]
meta_og_image = "https://www.zerostatic.io/theme/hugo-serif/hugo-serif-screenshot.png"
meta_linkedin_site = "https://www.linkedin.com/company/prodigit-ltd"
meta_github_organisation = "https://github.com/prodigit-org"

[params.services]
summary_truncate = 120 # How many characters to include in the summary of the services before truncating

[params.team]
summary_large_truncate = 120 # How many characters to include in the summary of the team bios (large layout) before truncating

[params.footer]
copyright_text = 'Copyright 2024 <a class="zerostatic" href="https://www.prodigit.org">www.prodigit.org</a>'

[menu]
# Main Menu
[[menu.main]]
name = "Services"
url = "/services/"
weight = 1

# [[menu.main]]
# name = "Team"
# url = "/team/"
# weight = 2

[[menu.main]]
name = "About"
url = "/about/"
weight = 3

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 4

# Footer Menu
[[menu.footer]]
name = "Home"
url = "/"
weight = 1

[[menu.footer]]
name = "Contact"
url = "/contact/"
weight = 2
